controller_manager:
  ros__parameters:
    update_rate: 50  # Hz, controller loop

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:
    publish_rate: 50.0

    # TF frames
    odom_frame_id: odom
    base_frame_id: base_footprint      # or base_link if that's what you use
    enable_odom_tf: true               # this gives you odom -> base_footprint in /tf

    # Link to your Webots joints (note the spaces!)
    left_wheel_names: ["left wheel motor"]
    right_wheel_names: ["right wheel motor"]

    # TurtleBot3 Burger geometry (approx)
    wheel_separation: 0.160            # meters
    wheel_radius: 0.033                # meters

    cmd_vel_timeout: 0.5               # seconds
    use_stamped_vel: false
    open_loop: false                   # uses wheel positions for odom